name: Build and Deploy to gh-pages

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Deploy to gh-pages
      run: |
        git add dist -f
        git -c user.name='GitHub Actions' -c user.email='<your-email>@example.com' commit -m 'Auto deploy to gh-pages'
        git subtree push --prefix dist origin gh-pages
