on:
  issues:
    types:
      - assigned

jobs:
  issue_assigned:
    name: issue_assigned
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@v1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
