name: Link PR
on:
  pull_request:
    types:
      - opened
      - reopened
      - review_requested
      - closed
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        id: get_issue_number
        with:
          script: |
            if (context.issue.number) {
              // Return issue number if present
              return context.issue.number;
            } else {
              // Otherwise return issue number from commit
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            }
          result-encoding: string
      - name: Issue number
        run: echo '${{steps.get_issue_number.outputs.result}}'
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Branch name
        run: echo '${{ steps.extract_branch.outputs.branch }}'
      - name: update-pull-request
        uses: kt3k/update-pr-description@v2
        with:
          destination_branch: ${{ steps.extract_branch.outputs.branch }}
          pr_body: "Closes ${{steps.get_issue_number.outputs.result}}"
          github_token: ${{ secrets.GH_TOKEN }}
